# Generated by Django 4.0.3 on 2022-04-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supers',
            new_name='Super',
        ),
    ]
