# Generated by Django 4.0.3 on 2022-04-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_supers_super'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='secondary_ablity',
            new_name='secondary_ability',
        ),
    ]
